[package]
name = "amdgpu_top"
version = "0.1.2"
edition = "2021"
license = "MIT"
homepage = "https://github.com/Umio-Yasuno/amdgpu_top"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdrm_amdgpu_sys = { git = "https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs" }
cursive = { version = "0.20", default-features = false, features = ["crossterm-backend"] }
procfs = { version = "0.15.1", default-features = false }

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1
