[package]
name = "amdgpu_top"
version = "0.1.3"
edition = "2021"
license = "MIT"
homepage = "https://github.com/Umio-Yasuno/amdgpu_top"
authors = ["Umio Yasuno <coelacanth_dream@proton.me>"]
description = """
Tool to displays AMDGPU usage.
The tool displays information gathered from performance counters (GRBM, GRBM2, CP_STAT), sensors, fdinfo, and AMDGPU driver.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libdrm_amdgpu_sys = { git = "https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs" }
cursive = { version = "0.20", default-features = false, features = ["crossterm-backend"] }
procfs = { version = "0.15.1", default-features = false }
ctrlc = { version = "3.2.5" }

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1

[package.metadata.deb]
depends = "libdrm2, libdrm-amdgpu1"
section = "utils"
