[package]
name = "amdgpu_top_gui"
version = "0.3.1"
edition = "2021"
license = "MIT"
homepage = "https://github.com/Umio-Yasuno/amdgpu_top"
authors = ["Umio Yasuno <coelacanth_dream@protonmail.com>"]
description = "GUI Library for amdgpu_top"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libamdgpu_top = { path = "../libamdgpu_top", version = "0.3.1" }
eframe = { version = "0.23.0", default-features = false, features = [ "default_fonts", "glow", "persistence", "wayland" ] }
egui_plot = { version = "0.23.0" }
i18n-embed = { version = "^0.14", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "^0.7"
rust-embed = { version = "8.0.0", features = ["debug-embed"] }
once_cell = "^1.18"
