[package]
name = "amdgpu_top_gui"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libamdgpu_top = { path = "../libamdgpu_top" }
eframe = { version = "^0.22.0", default-features = false, features = [ "default_fonts", "glow", "persistence", "wayland" ] }
i18n-embed = { version = "^0.13.9", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6.7"
rust-embed = { version = "6.8.1", features = ["debug-embed"] }
once_cell = "1.18.0"
