[package]
name = "amdgpu_top_gui"
license = "MIT AND OFL-1.1"
description = "GUI Library for amdgpu_top"
# version.workspace = true
# Workaround for cargo-i18n
# https://github.com/kellpossible/cargo-i18n/issues/97
version = "0.8.3"
edition.workspace = true
repository.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libamdgpu_top = { workspace = true }
eframe = { version = "^0.27", default-features = false, features = [ "default_fonts", "glow", "persistence", "wayland" ] }
egui_plot = { version = "^0.27" }
i18n-embed = { version = "^0.14", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "^0.7"
rust-embed = { version = "8.0.0", features = ["debug-embed"] }
once_cell = "^1.18"
