[package]
name = "libamdgpu_top"
version = "0.2.2"
edition = "2021"
license = "MIT"
homepage = "https://github.com/Umio-Yasuno/amdgpu_top"
authors = ["Umio Yasuno <coelacanth_dream@protonmail.com>"]
description = "A library for amdgpu_top"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.*" }
libdrm_amdgpu_sys = { version = "0.2.2", git = "https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs" }
