[package]
name = "libamdgpu_top"
license = "MIT"
description = "A library for amdgpu_top"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0" }
libdrm_amdgpu_sys = { version = "0.7.7", git = "https://github.com/Umio-Yasuno/libdrm-amdgpu-sys-rs" }
